use_frameworks!

target 'Koyomi_Example' do
  pod 'Koyomi', :path => '../'

  target 'Koyomi_Tests' do
#    inherit! :search_paths

#  pod 'Quick', '~> 0.9.3'
#  pod 'Nimble', '~> 4.1.0'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
        end
    end
end
